// USERS
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const FIREBASE_LOGIN_REQUEST = "FIREBASE_LOGIN_REQUEST";
export const FIREBASE_LOGIN_SUCCESS = "FIREBASE_LOGIN_SUCCESS";
export const FIREBASE_LOGIN_FAILURE = "FIREBASE_LOGIN_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

// CURRENCIES
export const GET_CURRENCIES_REQUEST = "GET_CURRENCIES_REQUEST";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAILURE = "GET_CURRENCIES_FAILURE";

// CATEGORIES
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const ADD_CATEGORIES_REQUEST = "ADD_CATEGORIES_REQUEST";
export const ADD_CATEGORIES_SUCCESS = "ADD_CATEGORIES_SUCCESS";
export const ADD_CATEGORIES_FAILURE = "ADD_CATEGORIES_FAILURE";

export const UPDATE_CATEGORIES_REQUEST = "UPDATE_CATEGORIES_REQUEST";
export const UPDATE_CATEGORIES_SUCCESS = "UPDATE_CATEGORIES_SUCCESS";
export const UPDATE_CATEGORIES_FAILURE = "UPDATE_CATEGORIES_FAILURE";

// WALLETS
export const GET_WALLETS_REQUEST = "GET_WALLETS_REQUEST";
export const GET_WALLETS_SUCCESS = "GET_WALLETS_SUCCESS";
export const GET_WALLETS_FAILURE = "GET_WALLETS_FAILURE";

export const ADD_WALLETS_REQUEST = "ADD_WALLETS_REQUEST";
export const ADD_WALLETS_SUCCESS = "ADD_WALLETS_SUCCESS";
export const ADD_WALLETS_FAILURE = "ADD_WALLETS_FAILURE";

export const UPDATE_WALLETS_REQUEST = "UPDATE_WALLETS_REQUEST";
export const UPDATE_WALLETS_SUCCESS = "UPDATE_WALLETS_SUCCESS";
export const UPDATE_WALLETS_FAILURE = "UPDATE_WALLETS_FAILURE";

// RECORD
export const GET_RECORD_REQUEST = "GET_RECORD_REQUEST";
export const GET_RECORD_SUCCESS = "GET_RECORD_SUCCESS";
export const GET_RECORD_FAILURE = "GET_RECORD_FAILURE";

export const GET_RECORD_ID_REQUEST = "GET_RECORD_ID_REQUEST";
export const GET_RECORD_ID_SUCCESS = "GET_RECORD_ID_SUCCESS";
export const GET_RECORD_ID_FAILURE = "GET_RECORD_ID_FAILURE";

export const ADD_RECORD_REQUEST = "ADD_RECORD_REQUEST";
export const ADD_RECORD_SUCCESS = "ADD_RECORD_SUCCESS";
export const ADD_RECORD_FAILURE = "ADD_RECORD_FAILURE";

export const UPDATE_RECORD_REQUEST = "UPDATE_RECORD_REQUEST";
export const UPDATE_RECORD_SUCCESS = "UPDATE_RECORD_SUCCESS";
export const UPDATE_RECORD_FAILURE = "UPDATE_RECORD_FAILURE";

export const UPDATE_RECORD_MEMBER_REQUEST = "UPDATE_RECORD_MEMBER_REQUEST";
export const UPDATE_RECORD_MEMBER_SUCCESS = "UPDATE_RECORD_MEMBER_SUCCESS";
export const UPDATE_RECORD_MEMBER_FAILURE = "UPDATE_RECORD_MEMBER_FAILURE";

// BALANCE
export const GET_BALANCE_REQUEST = "GET_BALANCE_REQUEST";
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILURE = "GET_BALANCE_FAILURE";

export const ADD_BALANCE_REQUEST = "ADD_BALANCE_REQUEST";
export const ADD_BALANCE_SUCCESS = "ADD_BALANCE_SUCCESS";
export const ADD_BALANCE_FAILURE = "ADD_BALANCE_FAILURE";

export const UPDATE_BALANCE_REQUEST = "UPDATE_BALANCE_REQUEST";
export const UPDATE_BALANCE_SUCCESS = "UPDATE_BALANCE_SUCCESS";
export const UPDATE_BALANCE_FAILURE = "UPDATE_BALANCE_FAILURE";

// TRANSACTIONS
export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAILURE = "GET_TRANSACTIONS_FAILURE";

export const ADD_TRANSACTIONS_REQUEST = "ADD_TRANSACTIONS_REQUEST";
export const ADD_TRANSACTIONS_SUCCESS = "ADD_TRANSACTIONS_SUCCESS";
export const ADD_TRANSACTIONS_FAILURE = "ADD_TRANSACTIONS_FAILURE";

export const UPDATE_TRANSACTIONS_REQUEST = "UPDATE_TRANSACTIONS_REQUEST";
export const UPDATE_TRANSACTIONS_SUCCESS = "UPDATE_TRANSACTIONS_SUCCESS";
export const UPDATE_TRANSACTIONS_FAILURE = "UPDATE_TRANSACTIONS_FAILURE";

// BUDGETS
export const GET_BUDGETS_REQUEST = "GET_BUDGETS_REQUEST";
export const GET_BUDGETS_SUCCESS = "GET_BUDGETS_SUCCESS";
export const GET_BUDGETS_FAILURE = "GET_BUDGETS_FAILURE";

export const GET_BUDGETS_ID_REQUEST = "GET_BUDGETS_ID_REQUEST";
export const GET_BUDGETS_ID_SUCCESS = "GET_BUDGETS_ID_SUCCESS";
export const GET_BUDGETS_ID_FAILURE = "GET_BUDGETS_ID_FAILURE";

export const ADD_BUDGETS_REQUEST = "ADD_BUDGETS_REQUEST";
export const ADD_BUDGETS_SUCCESS = "ADD_BUDGETS_SUCCESS";
export const ADD_BUDGETS_FAILURE = "ADD_BUDGETS_FAILURE";

export const UPDATE_BUDGETS_REQUEST = "UPDATE_BUDGETS_REQUEST";
export const UPDATE_BUDGETS_SUCCESS = "UPDATE_BUDGETS_SUCCESS";
export const UPDATE_BUDGETS_FAILURE = "UPDATE_BUDGETS_FAILURE";
